{"cells":[{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":18770,"status":"ok","timestamp":1696231719305,"user":{"displayName":"d a","userId":"06930156802328046202"},"user_tz":-540},"id":"b2TOP9QvPJnX","outputId":"9583fc23-ded0-4cad-b780-5358fbc0dca4"},"outputs":[{"name":"stdout","output_type":"stream","text":["Mounted at /content/drive\n"]}],"source":["#  06_prophet_trial_01.ipynb\n","#  prophetによる予測プログラムのパラメータ改善　20221130\n","#  Optunaが時間がかかるので手作業による最適値捜索\n","#  変化させるパラメータは'changepoint_prior_scale'のみ\n","#  こちらが本番。06_prophet_trial_00_testの結果から'changepoint_prior_scale'は0.001から0.01まで0.001間隔\n","#  出力値は最良のRMSEを得た場合のcsvとpngとRMSEとRMSE/停止水蒸気量\n","#  20230106 計算時間がかかりすぎるためパラメータ変更：30分間隔出力から１日間隔出力に変更。また、cps = 0.005に固定\n","\n","#  20230113 1日から10日までRMSEが出るように仕様変更\n","#  20230113 パラメータディフォルト値の場合のRMSEと比較追加\n","\n","#  prophetによる蒸気発生量予測：　20221102\n","\n","#  大藤手入れ　2023-5-19\n","#https://qiita.com/dcm_shimadas/items/8f049c4a258f0fbbfe23  <-  optuna参考ページ\n","from google.colab import drive\n","drive.mount('/content/drive')"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"mRe9vL3txllf"},"outputs":[],"source":["\n","\n","import os\n","os.chdir('/content/drive/MyDrive/Colab Notebooks/forecast/optuna_2')\n","\n","from sklearn.model_selection import TimeSeriesSplit\n","import glob\n","import pandas as pd\n","import numpy as np\n","import datetime as dt\n","from matplotlib import pyplot as plt\n","from prophet import Prophet\n","from sklearn.metrics import mean_squared_error\n"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":7310,"status":"ok","timestamp":1696231734773,"user":{"displayName":"d a","userId":"06930156802328046202"},"user_tz":-540},"id":"mlwHuF47Pu-Z","outputId":"43a84658-7e67-4484-9445-4bdb9bf68a7b"},"outputs":[{"name":"stdout","output_type":"stream","text":["Collecting optuna\n","  Downloading optuna-3.3.0-py3-none-any.whl (404 kB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m404.2/404.2 kB\u001b[0m \u001b[31m5.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hCollecting alembic>=1.5.0 (from optuna)\n","  Downloading alembic-1.12.0-py3-none-any.whl (226 kB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m226.0/226.0 kB\u001b[0m \u001b[31m8.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hCollecting cmaes>=0.10.0 (from optuna)\n","  Downloading cmaes-0.10.0-py3-none-any.whl (29 kB)\n","Collecting colorlog (from optuna)\n","  Downloading colorlog-6.7.0-py2.py3-none-any.whl (11 kB)\n","Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from optuna) (1.23.5)\n","Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from optuna) (23.1)\n","Requirement already satisfied: sqlalchemy>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from optuna) (2.0.20)\n","Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from optuna) (4.66.1)\n","Requirement already satisfied: PyYAML in /usr/local/lib/python3.10/dist-packages (from optuna) (6.0.1)\n","Collecting Mako (from alembic>=1.5.0->optuna)\n","  Downloading Mako-1.2.4-py3-none-any.whl (78 kB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m78.7/78.7 kB\u001b[0m \u001b[31m8.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hRequirement already satisfied: typing-extensions>=4 in /usr/local/lib/python3.10/dist-packages (from alembic>=1.5.0->optuna) (4.5.0)\n","Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy>=1.3.0->optuna) (2.0.2)\n","Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.10/dist-packages (from Mako->alembic>=1.5.0->optuna) (2.1.3)\n","Installing collected packages: Mako, colorlog, cmaes, alembic, optuna\n","Successfully installed Mako-1.2.4 alembic-1.12.0 cmaes-0.10.0 colorlog-6.7.0 optuna-3.3.0\n"]}],"source":["!pip install optuna\n","import optuna"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"8R9jR1x4SBUp"},"outputs":[],"source":["%matplotlib inline"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"zhiN18ynIyCK"},"outputs":[],"source":["# Prophetの出力をミュート\n","import logging\n","logging.getLogger(\"prophet\").setLevel(logging.ERROR)\n","logging.getLogger(\"cmdstanpy\").setLevel(logging.ERROR)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"K3hI-YYZNZxC"},"outputs":[],"source":["#取り出す期間\n","#予測失敗期間　20080204163500(06T)      20080409160500(06T)  20160820205000(15T)\n","#予測が大きく変わった期間 20160522170500(06T)     2010121192000(14T)    20101228192000(14T)  20160501205000 -> 20160502205000(15T)\n","#20160606205000 -> 20160607205000(15T)     20160609205000 -> 20160610205000(15T)\n","#ジャンプがある期間　　2008022163500(06T)    20160126170500(06T)   20160522170500(06T)\n","#学習失敗期間(学習が追えていない) 20160820205000->20160821205000->20160822205000(15T)       20200501145500(15T)\n","#この辺の期間を取り出して時間粒度やパラメータを変えて予測精度を上げていきたい。\n","#15Tの2016年の5月あたりがを取り出して色々試してみるのがいいかも (15T_20151113_20170411.csvとかでやってみる)\n","#20160802195500から20160924195500まではジャンプが大きいからこの期間の取り出しもあり。"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"OYegRGfNFDaQ"},"outputs":[],"source":["#ファイル読み込み\n","data_tmp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/forecast/001_segment_data_stop_judge/15T_20151113_20170411.csv',\n","                    index_col = 'date_time',\n","                    parse_dates = True)"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":10,"status":"ok","timestamp":1696231736020,"user":{"displayName":"d a","userId":"06930156802328046202"},"user_tz":-540},"id":"5pGX5HuCE2Dc","outputId":"5f6431cd-8886-4497-a408-520d2b0e710d"},"outputs":[{"name":"stdout","output_type":"stream","text":["75745\n","91009\n"]}],"source":["print(data_tmp.index.get_loc('2016-08-02 19:55:00'))\n","print(data_tmp.index.get_loc('2016-09-24 19:55:00'))"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":13,"status":"ok","timestamp":1696224083137,"user":{"displayName":"d a","userId":"06930156802328046202"},"user_tz":-540},"id":"7hobc9Kn1xaR","outputId":"f187ada7-fdb3-49c8-be04-2de8b21839b6"},"outputs":[{"data":{"text/plain":["288"]},"execution_count":8,"metadata":{},"output_type":"execute_result"}],"source":["data_tmp.index.get_loc('2016-08-04 19:55:00') - data_tmp.index.get_loc('2016-08-03 19:55:00')"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"ee5-15wtkcCg"},"outputs":[],"source":["# 変数の定義 学習粒度と予測対象期間は色々値を変えてみる(リストにしてループで回すのが良さそう)\n","learning_frequency = 60 #学習粒度(分) 5と30は実施済み [5,10,30,60,120]\n","learning_time = 20 # 学習期間　20日\n","prediction_time = 7 # 予測対象期間　7日 ここも値を変える"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"VFxrNJ1h2OWY"},"outputs":[],"source":["day_number_list = [1]"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"background_save":true,"base_uri":"https://localhost:8080/"},"id":"1PZn9I4SLqWw","outputId":"5c7d3872-9c10-4044-e819-cb0930754163"},"outputs":[{"name":"stdout","output_type":"stream","text":[" **  15T_20151113_20170411  の  20160804195500  から  20160824195500  までを学習します ** \n"," **  15T_20151113_20170411  の  20160824205500  から  20160831205500  までを予測します ** \n"]},{"name":"stderr","output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","Custom TB Handler failed, unregistering\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"name":"stdout","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-24-3f69a0d84448>\", line 127, in <cell line: 1>\n","    parameter_list.to_csv(parameter_path + prediction_start_date_time_str + '.csv')\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py\", line 211, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py\", line 3720, in to_csv\n","    return DataFrameRenderer(formatter).to_csv(\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py\", line 211, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py\", line 1189, in to_csv\n","    csv_formatter.save()\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/formats/csvs.py\", line 241, in save\n","    with get_handle(\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/common.py\", line 734, in get_handle\n","    check_parent_directory(str(handle))\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/common.py\", line 596, in check_parent_directory\n","    if not parent.is_dir():\n","  File \"/usr/lib/python3.10/pathlib.py\", line 1305, in is_dir\n","    return S_ISDIR(self.stat().st_mode)\n","  File \"/usr/lib/python3.10/pathlib.py\", line 1097, in stat\n","    return self._accessor.stat(self, follow_symlinks=follow_symlinks)\n","OSError: [Errno 107] Transport endpoint is not connected: 'learn_freq=60, prediction=7/008_pred_parameter01'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-24-3f69a0d84448>\", line 127, in <cell line: 1>\n","    parameter_list.to_csv(parameter_path + prediction_start_date_time_str + '.csv')\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py\", line 211, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py\", line 3720, in to_csv\n","    return DataFrameRenderer(formatter).to_csv(\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py\", line 211, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py\", line 1189, in to_csv\n","    csv_formatter.save()\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/formats/csvs.py\", line 241, in save\n","    with get_handle(\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/common.py\", line 734, in get_handle\n","    check_parent_directory(str(handle))\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/common.py\", line 596, in check_parent_directory\n","    if not parent.is_dir():\n","  File \"/usr/lib/python3.10/pathlib.py\", line 1305, in is_dir\n","    return S_ISDIR(self.stat().st_mode)\n","  File \"/usr/lib/python3.10/pathlib.py\", line 1097, in stat\n","    return self._accessor.stat(self, follow_symlinks=follow_symlinks)\n","OSError: [Errno 107] Transport endpoint is not connected: 'learn_freq=60, prediction=7/008_pred_parameter01'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 1972, in wrapped\n","    stb = handler(self,etype,value,tb,tb_offset=tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/dask/base.py\", line 79, in _clean_ipython_traceback\n","    stb = self.InteractiveTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-24-3f69a0d84448>\", line 127, in <cell line: 1>\n","    parameter_list.to_csv(parameter_path + prediction_start_date_time_str + '.csv')\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py\", line 211, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py\", line 3720, in to_csv\n","    return DataFrameRenderer(formatter).to_csv(\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py\", line 211, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py\", line 1189, in to_csv\n","    csv_formatter.save()\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/formats/csvs.py\", line 241, in save\n","    with get_handle(\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/common.py\", line 734, in get_handle\n","    check_parent_directory(str(handle))\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/common.py\", line 596, in check_parent_directory\n","    if not parent.is_dir():\n","  File \"/usr/lib/python3.10/pathlib.py\", line 1305, in is_dir\n","    return S_ISDIR(self.stat().st_mode)\n","  File \"/usr/lib/python3.10/pathlib.py\", line 1097, in stat\n","    return self._accessor.stat(self, follow_symlinks=follow_symlinks)\n","OSError: [Errno 107] Transport endpoint is not connected: 'learn_freq=60, prediction=7/008_pred_parameter01'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 1972, in wrapped\n","    stb = handler(self,etype,value,tb,tb_offset=tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/dask/base.py\", line 79, in _clean_ipython_traceback\n","    stb = self.InteractiveTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3571, in run_code\n","    self.CustomTB(etype, value, tb)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 1979, in wrapped\n","    stb = self.InteractiveTB.structured_traceback(*sys.exc_info())\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-24-3f69a0d84448>\", line 127, in <cell line: 1>\n","    parameter_list.to_csv(parameter_path + prediction_start_date_time_str + '.csv')\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py\", line 211, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py\", line 3720, in to_csv\n","    return DataFrameRenderer(formatter).to_csv(\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py\", line 211, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py\", line 1189, in to_csv\n","    csv_formatter.save()\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/formats/csvs.py\", line 241, in save\n","    with get_handle(\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/common.py\", line 734, in get_handle\n","    check_parent_directory(str(handle))\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/common.py\", line 596, in check_parent_directory\n","    if not parent.is_dir():\n","  File \"/usr/lib/python3.10/pathlib.py\", line 1305, in is_dir\n","    return S_ISDIR(self.stat().st_mode)\n","  File \"/usr/lib/python3.10/pathlib.py\", line 1097, in stat\n","    return self._accessor.stat(self, follow_symlinks=follow_symlinks)\n","OSError: [Errno 107] Transport endpoint is not connected: 'learn_freq=60, prediction=7/008_pred_parameter01'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 1972, in wrapped\n","    stb = handler(self,etype,value,tb,tb_offset=tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/dask/base.py\", line 79, in _clean_ipython_traceback\n","    stb = self.InteractiveTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3571, in run_code\n","    self.CustomTB(etype, value, tb)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 1979, in wrapped\n","    stb = self.InteractiveTB.structured_traceback(*sys.exc_info())\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}],"source":["for day_number in day_number_list:\n","    well = '15T_20151113_20170411'\n","    os.makedirs('learn_freq='+str(learning_frequency)+', prediction='+str(prediction_time)+'/008_pred_csv01/' , exist_ok=True)\n","    os.makedirs('learn_freq='+str(learning_frequency)+', prediction='+str(prediction_time)+'/008_pred_png01/' , exist_ok=True)\n","    os.makedirs('learn_freq='+str(learning_frequency)+', prediction='+str(prediction_time)+'/008_pred_rmse01/' , exist_ok=True)\n","    os.makedirs('learn_freq='+str(learning_frequency)+', prediction='+str(prediction_time)+'/008_pred_parameter01/' , exist_ok=True)\n","\n","    # 停止水蒸気量算出\n","    start_time        = data_tmp.index[75745+288*day_number]\n","    end_time          = start_time + dt.timedelta(days = 20)\n","    data_for_stop     = data_tmp[start_time:end_time]\n","    steamvol_for_stop = data_for_stop['steamvol'].mean()*(2/3)\n","    end_data          = data_tmp.index[91009]\n","    data_start_time   = start_time.strftime('%Y%m%d%H%M%S')\n","    data_end_time     = end_data.strftime('%Y%m%d%H%M%S')\n","\n","    # 出力フォルダ作成 # このへんmkdirs(, exist_ok = True) あたりを使用するとすっきりする（途中ディレクトリも作ってくれる）\n","    #os.makedirs('learn_freq='+str(learning_frequency)+', prediction='+str(prediction_time)+'/008_pred_csv01/'+ well + '/' + data_start_time + '_' + data_end_time , exist_ok=True)\n","    #os.makedirs('learn_freq='+str(learning_frequency)+', prediction='+str(prediction_time)+'/008_pred_png01/'+ well + '/' + data_start_time + '_' + data_end_time , exist_ok=True)\n","    #os.makedirs('learn_freq='+str(learning_frequency)+', prediction='+str(prediction_time)+'/008_pred_rmse01/'+ well + '/' + data_start_time + '_' + data_end_time , exist_ok=True)\n","    #os.makedirs('learn_freq='+str(learning_frequency)+', prediction='+str(prediction_time)+'/008_pred_parameter01/'+ well + '/' + data_start_time + '_' + data_end_time , exist_ok=True)\n","\n","    #pathをとっておく\n","    csv_path = 'learn_freq='+str(learning_frequency)+', prediction='+str(prediction_time)+'/008_pred_csv01/'\n","    png_path = 'learn_freq='+str(learning_frequency)+', prediction='+str(prediction_time)+'/008_pred_png01/'\n","    rmse_path = 'learn_freq='+str(learning_frequency)+', prediction='+str(prediction_time)+'/008_pred_rmse01/'\n","    parameter_path = 'learn_freq='+str(learning_frequency)+', prediction='+str(prediction_time)+'/008_pred_parameter01/'\n","\n","    # 学習、予測の日付時刻の取得\n","    start_date_time = data_tmp.index[75745+288*day_number] # 学習開始\n","    end_date_time = start_date_time + dt.timedelta(days = learning_time) # 学習終了\n","    prediction_start_date_time = end_date_time + dt.timedelta(minutes = learning_frequency) # 予測開始（学習が終了した後学習粒度の分だけ経ったら開始）\n","    prediction_end_date_time = prediction_start_date_time + dt.timedelta(days = prediction_time) # 予測終了\n","\n","    # 24時間ごとにシフトさせて予測\n","    prediction_start_date_time_list = []\n","    rmse_list = []\n","    thifted_time = 24\n","    counter = 1\n","\n","    start_date_time = data_tmp.index[75745+288*day_number]\n","    end_date_time = start_date_time + dt.timedelta(days = learning_time)\n","    start_date_time_str = str(start_date_time.strftime('%Y%m%d%H%M%S'))\n","    end_date_time_str = str(end_date_time.strftime('%Y%m%d%H%M%S'))\n","\n","    # 予測期間\n","    prediction_start_date_time = end_date_time + dt.timedelta(minutes = learning_frequency)\n","    prediction_end_date_time = prediction_start_date_time + dt.timedelta(days = prediction_time)\n","\n","    prediction_start_date_time_str = str(prediction_start_date_time.strftime('%Y%m%d%H%M%S'))\n","    prediction_end_date_time_str   = str(prediction_end_date_time.strftime('%Y%m%d%H%M%S'))\n","    print(\" ** \", well, \" の \", start_date_time_str, \" から \", end_date_time_str, \" までを学習します ** \")\n","    print(\" ** \", well, \" の \", prediction_start_date_time_str, \" から \", prediction_end_date_time_str, \" までを予測します ** \")\n","\n","    # 学習期間→train, 予測期間→test\n","    train = data_tmp[start_date_time:end_date_time]\n","    train = train.asfreq(str(learning_frequency)+'min') #学習粒度でリサンプリング\n","    test = data_tmp[prediction_start_date_time:prediction_end_date_time]\n","    test_length = len(test)\n","\n","    train.reset_index(inplace = True)\n","    test.reset_index(inplace = True)\n","\n","    train = train.rename(columns = {'date_time':'ds','steamvol':'y'})\n","    test  = test.rename( columns = {'date_time':'ds','steamvol':'y'})\n","\n","\n","    #\n","# Prophetによる予測\n","#ここからパラメータのチューニング\n","#ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー\n","    def objective(trial):\n","        params = {\n","            #'uncertainty_samples' : trial.suggest_int('uncertainty_samples', 100, 1000, 450),\n","            'changepoint_range' : trial.suggest_discrete_uniform('changepoint_range',0.8,0.95,0.001),\n","            'n_changepoints' : trial.suggest_int('n_changepoints',20,35),\n","            'changepoint_prior_scale' : trial.suggest_discrete_uniform('changepoint_prior_scale',0.001,0.5,0.001),\n","            'seasonality_prior_scale' : trial.suggest_discrete_uniform('seasonality_prior_scale',1,25,0.5),\n","            'seasonality_mode' : trial.suggest_categorical('seasonality_mode',['additive', 'multiplicative'])\n","            }\n","\n","        tss = TimeSeriesSplit(test_size = 5)\n","\n","        cv_mse = []\n","\n","        for fold, (train_index, valid_index) in enumerate(tss.split(train)):\n","            train_data = train.iloc[train_index] #訓練データ\n","            valid_data = train.iloc[valid_index] #検証データ\n","\n","            m = Prophet(**params)\n","\n","            m.fit(train_data)\n","\n","            df_future = m.make_future_dataframe(\n","                periods = len(valid_data),\n","                freq = str(learning_frequency)+'min'\n","            )\n","\n","            df_pred = m.predict(df_future)\n","            preds = df_pred.tail(len(valid_data))\n","\n","            val_mse = mean_squared_error(\n","                valid_data.y,\n","                preds.yhat\n","            )\n","            cv_mse.append(val_mse)\n","\n","        return np.mean(cv_mse)\n","\n","    optuna.logging.disable_default_handler()\n","\n","    study = optuna.create_study(direction = 'minimize')\n","    #n_trialsの値は1000でいいのか\n","    study.optimize(\n","        objective,\n","        n_trials = 1000,\n","        n_jobs = -1\n","        )\n","\n","\n","\n","    #ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー\n","\n","    #データフレームを作る(ベストパラメータを保存するため)\n","    parameter_list = pd.DataFrame()\n","    parameter_list['best_parameter'] = study.best_params\n","    parameter_list.to_csv(parameter_path + prediction_start_date_time_str + '.csv')\n","\n","    model_best = Prophet(**study.best_params)\n","    model_best.fit(train)\n","    future = model_best.make_future_dataframe(periods = test_length, freq = str(learning_frequency)+'min')\n","    pred_best  =  model_best.predict(future)\n","    pd.to_datetime(pred_best['ds'])\n","    pred_best = pred_best.set_index('ds')\n","\n","    merged_data_best = pd.merge(data_tmp,\n","                                pred_best,\n","                                right_index = True,\n","                                left_index = True,\n","                                how = 'inner')\n","\n","    merged_data_best = merged_data_best[start_date_time:prediction_end_date_time] # 学習期間も含めた\n","    merged_data_best.to_csv(csv_path + prediction_start_date_time_str + '.csv')\n","\n","\n","\n","    #\n","    # RMSE算出\n","    #\n","\n","    # 2日後までの 総計RMSE 算出\n","    actual_best = merged_data_best['steamvol']\n","    pred_data_best = merged_data_best['yhat']\n","    RMSE_best = np.sqrt(mean_squared_error(actual_best[0:47], pred_data_best[0:47]))\n","\n","    print(\" ** 2日間のRMSEは、\", round(RMSE_best, 3), \" でした **  \")\n","\n","    # 1日から7日までの 各日のRMSE 算出\n","    days_list = ['1day','2days','3days','4days','5days','6days','7days']\n","    rmse_list = []\n","    for i in [1,2,3,4,5,6,7]:\n","        start = merged_data_best.index[0] + dt.timedelta(days = 1*(i-1))\n","        end = start + dt.timedelta(days = 1) + dt.timedelta(minutes = learning_frequency)\n","        actual_tmp = merged_data_best['steamvol'][start:end]\n","        pred_data_tmp = merged_data_best['yhat'][start:end]\n","        try:\n","            rmse_tmp = np.sqrt(mean_squared_error(actual_tmp, pred_data_tmp))\n","        except:\n","            rmse_tmp = np.nan\n","        rmse_list.append(rmse_tmp)\n","\n","    '''\n","    # 比較のためのデフォルト値での予測\n","    model_default = Prophet(changepoint_prior_scale = 0.5)\n","    model_default.fit(train)\n","    future_default  =  model_default.make_future_dataframe(periods = test_length, freq = '60min')\n","    pred_default  =  model_default.predict(future_default)\n","    pd.to_datetime(pred_default['ds'])\n","    pred_default = pred_default.set_index('ds')\n","    merged_data_default = pd.merge(data_tmp,pred_default,right_index = True,left_index = True,how = 'inner')\n","    merged_data_default = merged_data_default[prediction_start_date_time:prediction_end_date_time]\n","    actual_00 = merged_data_default['steamvol']\n","    pred_data_00 = merged_data_default['yhat']\n","    RMSE_00 = np.sqrt(mean_squared_error(actual_00[0:47], pred_data_00[0:47]))# 一応算出：改善度合いをみるため\n","    '''\n","\n","    #\n","    # プロット\n","    #\n","    plt.rcParams['figure.figsize'] = (20,5)\n","\n","    plt.plot(merged_data_best['steamvol'], # 実測値\n","            color = 'black',\n","            label = 'actual_data')\n","\n","    plt.plot(merged_data_best.loc[start_date_time:end_date_time,\n","                                'yhat'], # 学習期間\n","            color = 'cyan',\n","            label = 'Training ')\n","\n","    plt.plot(merged_data_best.loc[prediction_start_date_time:prediction_end_date_time,\n","                                'yhat'], # 予測期間\n","            color = 'blue',\n","            label = 'Prediction: best RMSE = ' + str(round(RMSE_best, 5)))\n","\n","    plt.axvline(prediction_start_date_time,\n","                color='blue', linestyle='--')\n","\n","    # plt.plot(merged_data_default['yhat'],color = 'red',label = 'default RMSE = ' + str(RMSE_00)) # デフォルト（cps=0.5）プロット\n","\n","    plt.legend()\n","    plt.grid()\n","    plt.title(str(well)+'  learning_freq = '+str(learning_frequency)+ 'minutes    prediction_time = ' +str(prediction_time)+'days', loc = \"left\")\n","\n","    plt.savefig(png_path + prediction_start_date_time_str + '.png')\n","    plt.clf()\n","\n","    print(\" ** plot : \", png_path + prediction_start_date_time_str , \" .png を書き出しました ** \")\n","\n","\n","    # RMSE出力\n","    df_rmse = pd.DataFrame()\n","    df_rmse['days'] = days_list\n","    df_rmse['RMSE'] = rmse_list\n","    df_rmse['normed_RMSE'] = rmse_list/steamvol_for_stop\n","    df_rmse = df_rmse.set_index('days')\n","    df_rmse = df_rmse.T\n","    df_rmse['RMSE_best_total'] = [RMSE_best,RMSE_best/steamvol_for_stop]\n","    # df_rmse['RMSE_default_total'] = [RMSE_00,RMSE_00/steamvol_for_stop]\n","    df_rmse = df_rmse.T\n","\n","    df_rmse.to_csv(rmse_path + prediction_start_date_time_str + '.csv')\n","\n","\n","    counter = counter + 1\n","    print(\"============================================\")\n"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"rNL6sg_BLQXi"},"outputs":[],"source":[]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":252,"status":"ok","timestamp":1694436386334,"user":{"displayName":"d a","userId":"06930156802328046202"},"user_tz":-540},"id":"TD96kxHGN6Mv","outputId":"1af5126d-5282-4c67-8718-69863647a36c"},"outputs":[{"name":"stdout","output_type":"stream","text":["{'changepoint_range': 0.8580000000000001, 'n_changepoints': 25, 'changepoint_prior_scale': 0.057, 'seasonality_prior_scale': 18.5, 'seasonality_mode': 'additive'}\n"]}],"source":["print(study.best_params)"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":86},"executionInfo":{"elapsed":1939,"status":"ok","timestamp":1694437069332,"user":{"displayName":"d a","userId":"06930156802328046202"},"user_tz":-540},"id":"oUusADseeZLO","outputId":"1c74e55e-bea7-460e-f5bc-5756f6ab91c1"},"outputs":[{"name":"stdout","output_type":"stream","text":[" ** 2日間のRMSEは、 0.208  でした **  \n"," ** plot :  learn_freq=60, prediction=7/008_pred_png01/15T_20151113_20170411/20160806195500_20160924195500/20160826205500  .png を書き出しました ** \n","============================================\n"]},{"data":{"text/plain":["<Figure size 2000x500 with 0 Axes>"]},"metadata":{},"output_type":"display_data"}],"source":["\n","\n"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"d70PYnMj34bI"},"outputs":[],"source":["def objective_variable(train,valid):\n","  def objective(trial):\n","            params = {\n","      'changepoint_range' : trial.suggest_float('changepoint_range',0.8,0.95, step = 0.001),\n","      'n_changepoints' : trial.suggest_int('n_changepoints',20,35),\n","      'changepoint_prior_scale' : trial.suggest_float('changepoint_prior_scale',0.001,0.5),\n","      'seasonality_prior_scale' : trial.suggest_float('seasonality_prior_scale',0.01,10),\n","      'seasonality_mode' : trial.suggest_categorical('seasonality_mode',['additive', 'multiplicative']),\n","        }\n","            # fit_model\n","            m=Prophet(**params)\n","            m.fit(train)\n","            future = m.make_future_dataframe(periods=len(valid))\n","\n","            forecast = m.predict(future)\n","            valid_forecast = forecast.tail(len(valid))\n","\n","            val_mape = np.mean(np.abs((valid_forecast.yhat-valid.y)/valid.y))*100\n","            return val_mape\n","  return objective\n","\n"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"eUpZ7Zk9Y-0t"},"outputs":[],"source":["def optuna_parameter(train,valid):\n","    study = optuna.create_study(sampler=optuna.samplers.RandomSampler(seed=42))\n","    study.optimize(objective_variable(train,valid), timeout=1000)\n","    optuna_best_params = study.best_params\n","\n","    return study"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"alC7rh5Yj6xg"},"outputs":[],"source":[]}],"metadata":{"colab":{"provenance":[{"file_id":"1Wf7kTxri-wJjdgj27NoRTvp7QeWZi2Nt","timestamp":1694440812236},{"file_id":"166SoaRJgqunxtxR9yJVVwfTijut59kWI","timestamp":1694347870320},{"file_id":"1APjVHOh9ki1CYkolhWAIuj5CcBJKMzZl","timestamp":1694254128343},{"file_id":"1qfldmMVSGp8uvvZAGlLQiAKqjN1PSxTB","timestamp":1693886084536},{"file_id":"1O2VzdaN7hFH1x-8Lfr9VH7RRK-7CH78r","timestamp":1693381167101},{"file_id":"122Ud0D5A4nrw_Q0PMPXNEGv9qfzswQKb","timestamp":1691824828209}]},"kernelspec":{"display_name":"Python 3","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.11.3"}},"nbformat":4,"nbformat_minor":0}